FROM golang:1.19-alpine AS builder

WORKDIR /app
COPY go.mod .
COPY go.sum .


RUN go mod download

COPY . .

RUN go build -o /application ./cmd/function/sync_tokens/main.go

FROM alpine

COPY --from=builder /application /app/application

ENTRYPOINT ./app/application